// <auto-generated />
namespace University.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deNuevok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deNuevok));
        
        string IMigrationMetadata.Id
        {
            get { return "202202142234448_ de Nuevok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
